#!/www/server/panel/pyenv/bin/python
#coding: utf-8
# +-------------------------------------------------------------------
# | 宝塔Linux面板
# +-------------------------------------------------------------------
# | Copyright (c) 2015-2099 宝塔软件(http://bt.cn) All rights reserved.
# +-------------------------------------------------------------------
# | Author: 黄文良 <287962566@qq.com>
# +-------------------------------------------------------------------
import sys
import os
os.chdir('/www/server/panel')
sys.path.insert(0,'class/')
sys.path.insert(0,'plugin/oos')
import public

main_pid = 'logs/oos.pid'
if os.path.exists(main_pid):
    os.system("kill -9 $(cat {}) &> /dev/null".format(main_pid))
pid = os.fork()
if pid: sys.exit(0)

os.umask(0)
os.setsid()

_pid = os.fork()
if _pid:
    public.writeFile(main_pid,str(_pid))
    sys.exit(0)

sys.stdout.flush()
sys.stderr.flush()
task_log_file='logs/oos.log'
if not os.path.exists(task_log_file):
    open(task_log_file,'w+').close()
    
err_f = open(task_log_file,'a+')
os.dup2(err_f.fileno(),sys.stderr.fileno())
err_f.close()

import oos_main
p = oos_main.oos_main()
p.run_task()