#!/bin/sh



# This is a script that enables Snoopy system-wide.
# You have to run this script as a privileged user.
# This script is also run when you execute "make enable".



### Where is the library installed?
#
LIBDIR="/usr/local/usranalyse/lib"



### Check Snoopy installation
#
if [ ! -r $LIBDIR/libusranalyse.so ]; then
    echo
    echo "USRANALYSE ERROR: $LIBDIR/libusranalyse.so is not installed or is not readable"
    echo
    exit 1
fi



### Check user that is running this script
#
touch /etc/ld.so.preload
if [ ! -w /etc/ld.so.preload ]; then
    echo
    echo 'USRANALYSE ERROR: /etc/ld.so.preload not writable - are you running this script as a unprivileged user?'
    echo
    exit 1
fi



### Do the actual installation
#
COUNT=`grep -Ec "/(lib)?usranalyse.so" /etc/ld.so.preload`
if [ "$COUNT" -gt "1" ]; then
    echo
    echo "USRANALYSE ERROR: Multiple instances of (lib)usranalyse.so found in /etc/ld.so.preload. Unable to proceed."
    echo
    exit 1
elif [ "$COUNT" -eq "1" ]; then
    echo -n "USRANALYSE: Removing from /etc/ld.so.preload: "
    cat /etc/ld.so.preload | grep -E "/(lib)?usranalyse.so"
    sed -i "/\/\(lib\)\?usranalyse.so/d" /etc/ld.so.preload
fi

echo "USRANALYSE: Adding to /etc/ld.so.preload:     $LIBDIR/libusranalyse.so"
usranso=`ls -l /usr/local/usranalyse/lib/libusranalyse.so | awk '{print $5}'`
if [ $usranso -gt 0 ];then
echo "$LIBDIR/libusranalyse.so" >> /etc/ld.so.preload
echo "USRANALYSE: install sucessful,."
echo "USRANALYSE: Enabled."
fi
